transformer:
  encoder_layer: 2
  encoder_head: 2
  encoder_hidden: 256
  decoder_layer: 6
  decoder_head: 2
  decoder_hidden: 256
  conv_filter_size: 1024
  conv_kernel_size: [9, 1]
  encoder_dropout: 0.2
  decoder_dropout: 0.2

denoiser:
  denoiser_hidden: 512
  denoiser_dropout: 0.2
  residual_layers: 20
  residual_channels: 256
  noise_schedule_naive: 'cosine'
  noise_schedule_shallow: 'linear'
  timesteps: 100
  K_step: 71
  max_beta: 0.06
  s: 0.008
  keep_bins: 80

variance_predictor:
  filter_size: 256
  kernel_size: 3
  dropout: 0.5
  predictor_grad: 0.1

variance_embedding:
  pitch_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the pitch values are not normalized during preprocessing
  energy_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing
  n_bins: 256

multi_speaker: False

max_seq_len: 1000

vocoder:
  model: "HiFi-GAN" # support 'HiFi-GAN', 'MelGAN'
  speaker: "LJSpeech" # support  'LJSpeech', 'universal'
