dataset: "LJSpeech"

path:
  corpus_path: "/mnt/nfs2/speech-datasets/en/LJSpeech-1.1"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/LJSpeech"
  preprocessed_path: "./preprocessed_data/LJSpeech_cwt"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    pitch_type: "cwt" # frame|ph|cwt
    pitch_norm: "log" # standard|log
    pitch_norm_eps: 0.000000001
    pitch_ar: False
    with_f0: True
    with_f0cwt: True
    use_uv: True
    feature: "frame_level" # only support 'frame_level'
    f0_mean: 214.31683793057
    f0_std: 63.97520977575229
    cwt_scales: -1
  energy:
    feature: "frame_level" # only support 'frame_level'
    normalization: True
